.TH DHCP24 5 "31 OCTOBER 24"
.SH NAME
dhcp24 /- \fBDie Heilbronner Chaos Party 2024\fP
.SH SYNOPSIS
\fBdhcp\fP [ \fB-h ] [ \fB-l\fP \fIlocation\fP ] [ \fB-t\fP \fItime\fP ] [ \fB-v\fP \fIversion\fP ] [ \fB-m\fP \fImore\fP ]
.SH DESCRIPTION
\fBdhcp\fP - Die Heilbronner Chaos Party is an Event organized by Code for Heilbronn (CFHN) for decentralized, 
distributed, collaborative, hyperinflated Chaos and F.U.N..
The event will take place from the 31.10.2024 - 3.11.2024 in Heilbronn.
.SS Options
.TP
.B -h
Shows this info text.
.TP
.B -v
This is version 1. There may be others.
.TP
.B -l location
This events location.
.TP
.B -t time
This event will take place from \fI31.10.2024\fP to \fI03.11.2024\fP
.TP
.B -m more
See more at \fIdhcp.cfhn.it\fP
.SH "SEE ALSO"
cfhn.it(5), talks.dhcp.cfhn.it(5), tickets.dhcp.cfhn.it()
.SH BUGS
May require human intervention if mate
supply is exhausted.